# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Update version files"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 0 * * *"

jobs:
    fetch-versions:
        name: "PHP ${{ matrix.php-versions }} fetch versions on ubuntu-latest OS with ${{ matrix.dependencies }} dependencies"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-versions: ["8.0"]
                dependencies: ["locked"]

        env:
            key: "fetch-versions-linux-v1" # change key (version) to clear cache
            extensions: "mbstring"
            ini-values: "date.timezone=Europe/Berlin, opcache.enable_cli=0, serialize_precision=14"
            tools: "composer"

        steps:
            - name: "Git checkout"
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - name: "Setup cache environment"
              id: "cache-env"
              uses: "shivammathur/cache-extensions@v1"
              with:
                  php-version: "${{ matrix.php-versions }}"
                  extensions: "${{ env.extensions }}"
                  key: "${{ env.key }}"

            - name: "Cache extensions"
              uses: "actions/cache@v2"
              with:
                  path: "${{ steps.cache-env.outputs.dir }}"
                  key: "${{ steps.cache-env.outputs.key }}"
                  restore-keys: "${{ steps.cache-env.outputs.key }}"

            - name: "Setup PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php-versions }}"
                  extensions: "${{ env.extensions }}"
                  ini-values: "${{ env.ini-values }}"
                  tools: "${{ env.tools }}"
                  coverage: "pcov"

            - name: "Setup Problem Matchers for PHP"
              run: "echo '::add-matcher::${{ runner.tool_cache }}/php.json'"

            - name: "Check PHP Version"
              run: "php -v"

            - name: "List all php extensions with versions"
              run: "php -r 'foreach (get_loaded_extensions() as $extension) echo $extension . \" \" . phpversion($extension) . PHP_EOL;'"

            - name: "Configure Container"
              env:
                  GIT_USER_EMAIL: "${{ secrets.GIT_USER_EMAIL }}"
                  GIT_USER_USERNAME: "${{ secrets.GIT_USER_USERNAME }}"
              run: |
                  EMAIL=${GIT_USER_EMAIL:-"github-actions[bot]@users.noreply.github.com"}
                  NAME=${GIT_USER_USERNAME:-"github-actions-shell"}

                  git config --global user.email "${EMAIL}"
                  git config --global user.name "${NAME}"

            - name: "Check Composer Version"
              run: "composer -V"

            - name: "Validate composer.json and composer.json"
              run: "composer validate --strict"

            - name: "Install dependencies with Composer"
              uses: "ramsey/composer-install@v1"
              with:
                  dependency-versions: "${{ matrix.dependencies }}"

            - name: "Fetch versions"
              run: "php bin/versions.php"
              env:
                  VERSIONS_GITHUB_TOKEN: "${{ secrets.VERSIONS_GITHUB_TOKEN }}"

            - name: "Commit modified files"
              uses: "stefanzweifel/git-auto-commit-action@v4.9.1"
              with:
                  commit_author: "Daniel Bannert <d.banner@anolilab.de>"
                  commit_message: "feat: updated versions files"
                  commit_user_email: "d.banner@anolilab.de"
                  commit_user_name: "prisis"
